version: '3'

services:
  etherpad:
    image: node:16
    container_name: etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./:/etherpad
    working_dir: /etherpad
    command: bash -c "pnpm install && pnpm run dev"
    networks:
      - etherpad-network
    restart: unless-stopped

  etherdraw:
    image: anybox/etherdraw:stable
    container_name: etherdraw-server
    ports:
      - "9002:9002"
    volumes:
      - ./etherdraw/settings.json:/srv/etherdraw/draw/settings.json
    networks:
      - etherpad-network
    restart: unless-stopped

networks:
  etherpad-network:
    driver: bridge
